services:
  mysql:
    image: mysql:8.0 # Wykorzystuje najnowszy obraz MySQL
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root # Hasło do użytkownika root
      MYSQL_DATABASE: shop_co_db # Nazwa bazy danych do stworzenia przy starcie
      MYSQL_USER: user # Nazwa użytkownika
      MYSQL_PASSWORD: userpass # Hasło dla użytkownika
    ports:
      - "3306:3306" # Mapowanie portów (port na hoście -> port w kontenerze)
    volumes:
      - mysql-data:/var/lib/mysql # Użycie wolumenu do przechowywania danych
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "user",
          "-puserpass",
        ]
      interval: 10s # Sprawdzaj co 10 sekund
      timeout: 5s # Maksymalny czas oczekiwania na odpowiedź
      retries: 3 # Ilość prób przed uznaniem, że kontener jest "niezdrowy"
      start_period: 30s # Poczekaj 30 sekund przed uruchomieniem healthcheck (ważne dla wolniejszych baz danych)

  backend:
    build: ./backend
    container_name: shop-co-backend
    environment:
      - DB_HOST=mysql-db
      - DB_USER=user
      - DB_PASSWORD=userpass
      - DB_NAME=shop_co_db
      - DB_PORT=3306
      - JWT_SECRET=my_password_very_very
      - NODE_ENV=development
      - BACKEND_PORT=3005
    ports:
      - "3005:3005" # Mapowanie portów dla aplikacji Node.js
    depends_on:
      mysql:
        condition: service_healthy # Poczekaj, aż MySQL przejdzie testy healthcheck
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: shop-co-frontend
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Ensures proper functioning of dependencies
    networks:
      - app-network
    command: npm run dev # Launches Vite development server

volumes:
  mysql-data: # Definicja wolumenu do przechowywania danych MySQL

networks:
  app-network:
    driver: bridge
